package org.margin.server.notifications;

public enum NotificationType {
    ANNOUNCEMENT,
    MISSED_CALL,
    ADDED_TO_MARGIN,
    INVITED_TO_MARGIN,
    CONVERSATION_INVITE,
    MESSAGE_REACTION,
    THREAD_REPLY,
    SUBSCRIPTION_UPGRADED,
    SUBSCRIPTION_PAYMENT_FAILED,
    SUBSCRIPTION_LIMIT_WARNING,
}