spring.application.name=margin-server

# Will use SPRING_DATASOURCE_URL from env, or default to postgres service name
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/margindb}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

spring.flyway.clean-disabled=false

