spring.application.name=margin-server

# Will use SPRING_DATASOURCE_URL from env, or default to postgres service name
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/margindb}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

spring.flyway.clean-disabled=false

federation.server-domain=localhost:8080
federation.public-endpoint=http://localhost:8080