CREATE TABLE announcements
(
    announcement_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    margin_id       BIGINT       NOT NULL,
    author_id       BIGINT       NOT NULL,
    title           VARCHAR(255) NOT NULL,
    content         TEXT         NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    edited_at       TIMESTAMP,
    CONSTRAINT pk_announcement PRIMARY KEY (announcement_id),
    CONSTRAINT fk_announcement_margin FOREIGN KEY (margin_id) REFERENCES margins (margin_id),
    CONSTRAINT fk_announcement_author FOREIGN KEY (author_id) REFERENCES users (id)
);

CREATE INDEX idx_announcement_margin_id ON announcements (margin_id);
CREATE INDEX idx_announcement_author_id ON announcements (author_id);