CREATE TABLE users
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username            VARCHAR(50)                             NOT NULL,
    email               VARCHAR(255)                            NOT NULL,
    password            VARCHAR(255)                            NOT NULL,
    role                SMALLINT                                NOT NULL DEFAULT 0,
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    profile_picture_url VARCHAR(500),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

CREATE TABLE user_encryption
(
    user_id               BIGINT NOT NULL,
    public_key            VARCHAR(2048),
    encrypted_private_key VARCHAR(4096),
    salt                  VARCHAR(512),
    iv                    VARCHAR(512),
    CONSTRAINT pk_user_encryption PRIMARY KEY (user_id),
    CONSTRAINT fk_user_encryption_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE user_security
(
    user_id                   BIGINT  NOT NULL,
    failed_login_attempts     INTEGER NOT NULL DEFAULT 0,
    last_failed_login_attempt TIMESTAMP WITHOUT TIME ZONE,
    account_locked_until      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_user_security PRIMARY KEY (user_id),
    CONSTRAINT fk_user_security_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);