CREATE TABLE notification
(
    notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    recipient_id    BIGINT                      NOT NULL,
    sender_id       BIGINT,
    margin_id       BIGINT                      NOT NULL,
    type            VARCHAR(255)                NOT NULL,
    reference_id    BIGINT,
    seen            BOOLEAN                     NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_notification PRIMARY KEY (notification_id)
);

ALTER TABLE notification
    ADD CONSTRAINT FK_NOTIFICATION_ON_RECIPIENT FOREIGN KEY (recipient_id) REFERENCES users (id);

ALTER TABLE notification
    ADD CONSTRAINT FK_NOTIFICATION_ON_SENDER FOREIGN KEY (sender_id) REFERENCES users (id);