CREATE TABLE spaces
(
    space_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    visibility  VARCHAR(50)                             NOT NULL,
    margin_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_spaces PRIMARY KEY (space_id),
    CONSTRAINT fk_spaces_margin FOREIGN KEY (margin_id) REFERENCES margins (margin_id)
);

CREATE TABLE space_members
(
    space_member_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    space_id        BIGINT                                  NOT NULL,
    user_id         BIGINT                                  NOT NULL,
    role            VARCHAR(50)                             NOT NULL,
    joined_at       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_space_members PRIMARY KEY (space_member_id),
    CONSTRAINT fk_space_members_space FOREIGN KEY (space_id) REFERENCES spaces (space_id),
    CONSTRAINT fk_space_members_user FOREIGN KEY (user_id) REFERENCES users (id)
);