CREATE TABLE spaces
(
    space_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    visibility  SMALLINT                                NOT NULL,
    margin_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_spaces PRIMARY KEY (space_id)
);

ALTER TABLE spaces
    ADD CONSTRAINT FK_SPACES_ON_MARGIN FOREIGN KEY (margin_id) REFERENCES margins (margin_id);