CREATE TABLE channels
(
    channel_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    space_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_channels PRIMARY KEY (channel_id)
);

ALTER TABLE channels
    ADD CONSTRAINT FK_CHANNELS_ON_SPACE FOREIGN KEY (space_id) REFERENCES spaces (space_id);