CREATE TABLE conversations
(
    conversation_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type            VARCHAR(20)                             NOT NULL,
    name            VARCHAR(100),
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    channel_id      BIGINT,
    CONSTRAINT pk_conversations PRIMARY KEY (conversation_id)
);

ALTER TABLE conversations
    ADD CONSTRAINT FK_CONVERSATIONS_ON_CHANNEL FOREIGN KEY (channel_id) REFERENCES channels (channel_id);