CREATE TABLE users
(
    user_id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username                  VARCHAR(50)                             NOT NULL,
    email                     VARCHAR(255)                            NOT NULL,
    password                  VARCHAR(255)                            NOT NULL,
    role                      SMALLINT                                NOT NULL,
    created_at                TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    public_key                VARCHAR(2048),
    encrypted_private_key     VARCHAR(4096),
    salt                      VARCHAR(512),
    iv                        VARCHAR(512),
    failed_login_attempts     INTEGER                                 NOT NULL,
    last_failed_login_attempt TIMESTAMP WITHOUT TIME ZONE,
    account_locked_until      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);