CREATE TABLE message_reactions
(
    reaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message_id  BIGINT                                  NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    emoji       VARCHAR(16)                             NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_message_reactions PRIMARY KEY (reaction_id),
    CONSTRAINT fk_message_reactions_message FOREIGN KEY (message_id) REFERENCES messages (message_id) ON DELETE CASCADE,
    CONSTRAINT fk_message_reactions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uc_message_reactions UNIQUE (message_id, user_id, emoji)
);
