CREATE TABLE margins
(
    margin_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    visibility  VARCHAR(50)                             NOT NULL,
    icon_url    VARCHAR(500),
    CONSTRAINT pk_margins PRIMARY KEY (margin_id)
);

CREATE TABLE margin_members
(
    margin_member_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    margin_id        BIGINT                                  NOT NULL,
    user_id          BIGINT                                  NOT NULL,
    role             VARCHAR(50)                             NOT NULL,
    joined_at        TIMESTAMP,
    CONSTRAINT pk_margin_members PRIMARY KEY (margin_member_id),
    CONSTRAINT fk_margin_members_margin FOREIGN KEY (margin_id) REFERENCES margins (margin_id),
    CONSTRAINT fk_margin_members_user FOREIGN KEY (user_id) REFERENCES users (id)
);