CREATE TABLE channels
(
    channel_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    description  VARCHAR(255)                            NOT NULL,
    channel_type SMALLINT                                NOT NULL,
    space_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_channels PRIMARY KEY (channel_id),
    CONSTRAINT fk_channels_space FOREIGN KEY (space_id) REFERENCES spaces (space_id)
);