CREATE TABLE calls
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    caller_id        BIGINT                                  NOT NULL,
    receiver_id      BIGINT                                  NOT NULL,
    status           VARCHAR(50)                             NOT NULL,
    type             VARCHAR(50)                             NOT NULL,
    offered_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    answered_at      TIMESTAMP WITHOUT TIME ZONE,
    ended_at         TIMESTAMP WITHOUT TIME ZONE,
    duration_seconds INTEGER,
    CONSTRAINT pk_calls PRIMARY KEY (id),
    CONSTRAINT fk_calls_caller FOREIGN KEY (caller_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT fk_calls_receiver FOREIGN KEY (receiver_id) REFERENCES users (id) ON DELETE SET NULL
);