CREATE TABLE direct_messages
(
    direct_message_id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    from_user_id     BIGINT                                  NOT NULL,
    to_user_id       BIGINT                                  NOT NULL,
    message          VARCHAR(5000),
    is_read          BOOLEAN,
    is_edited        BOOLEAN,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_direct_messages PRIMARY KEY (direct_message_id)
);