CREATE TABLE channel_messages
(
    channel_message_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    from_user_id       BIGINT                                  NOT NULL,
    to_channel_id      BIGINT                                  NOT NULL,
    message            VARCHAR(5000),
    is_edited          BOOLEAN,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_channel_messages PRIMARY KEY (channel_message_id)
);

ALTER TABLE channel_messages
    ADD CONSTRAINT FK_CHANNEL_MESSAGES_ON_SPACE FOREIGN KEY (to_channel_id) REFERENCES channels (channel_id);