CREATE TABLE calls
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    caller_id        BIGINT                                  NOT NULL,
    receiver_id      BIGINT                                  NOT NULL,
    status           VARCHAR(255)                            NOT NULL,
    type             VARCHAR(255)                            NOT NULL,
    sdp              TEXT,
    offered_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    answered_at      TIMESTAMP WITHOUT TIME ZONE,
    ended_at         TIMESTAMP WITHOUT TIME ZONE,
    duration_seconds INTEGER,
    CONSTRAINT pk_calls PRIMARY KEY (id)
);