CREATE TABLE margins
(
    margin_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    visibility  SMALLINT                                NOT NULL,
    CONSTRAINT pk_margins PRIMARY KEY (margin_id)
);